### ISSUE TITLE
Rename function

### ISSUE THREAD

**Issue by ivan-unfolds** [fac25/week5-Alex-Sumithra-ClientReactApp#28]
It's confusing that this function begins with `set..` as this is usually reserved for hooks. You might want to choose another name to avoid this.

https://github.com/fac25/week5-Alex-Sumithra-ClientReactApp/blob/746fba3cb1527498770624e25f38a44a298d18d8/src/Components/Board.jsx#L44

**Comment by Sumithra-Suresh** [comment]
Thanks. We have changed the function name.
